"""Generate every Focus .vstheme from the shared palette table.

The Focus family is six dark themes that share a structure and differ only in
colour, so the structure lives here once and the palettes live in
scripts/focuspalette.py - the same table the VS Code and JetBrains generators
read. Not shipped in the VSIX: run by hand when a palette changes, output
committed.

Usage:  python gen-themes.py [outdir]
"""
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "scripts"))

from focuspalette import (  # noqa: E402
    AA, CLOSEST_REPORTED, PALETTES, REPORTED, SEPARATED,
    contrast, derive, hue_gap, to_hsl,
)

OUTDIR = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Theme template
# ---------------------------------------------------------------------------
# Category GUIDs and colour names are Visual Studio's own; only the Source values
# differ between themes.

TEMPLATE = """<Themes>
  <!-- %(name)s
       %(desc)s
       Surfaces: editor #%(bg)s / chrome #%(chrome)s / panel #%(panel)s
                 raised #%(raised)s / border #%(border)s / selection #%(sel)s
       Text:     #%(text)s primary, #%(comment)s comment, #%(muted)s gutter
       Types:    class #%(class)s, interface #%(interface)s, record #%(record)s,
                 struct #%(struct)s, enum #%(enum)s
       Syntax:   keyword #%(keyword)s, method #%(method)s, variable #%(variable)s,
                 operator #%(operator)s, string #%(string)s, number #%(number)s
       Accent:   #%(accent)s

       Generated by gen-themes.py - edit the palette there, not this file. -->
  <Theme Name="%(name)s" GUID="%(guid)s" FallbackId="%(fallback)s">

    <Category Name="Shell" GUID="{73708ded-2d56-4aad-b8eb-73b20d3f4bff}">
      <Color Name="AccentFillDefault">
        <Background Type="CT_RAW" Source="FF%(accent)s"/>
      </Color>
      <Color Name="AccentFillSecondary">
        <Background Type="CT_RAW" Source="E5%(accent)s"/>
      </Color>
      <Color Name="AccentFillTertiary">
        <Background Type="CT_RAW" Source="CC%(accent)s"/>
      </Color>
      <Color Name="SolidBackgroundFillTertiary">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
      </Color>
      <Color Name="SolidBackgroundFillQuaternary">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
      </Color>
      <Color Name="SurfaceBackgroundFillDefault">
        <Background Type="CT_RAW" Source="FF%(panel)s"/>
      </Color>
      <Color Name="TextFillSecondary">
        <Background Type="CT_RAW" Source="B2%(text)s"/>
      </Color>
    </Category>

    <Category Name="ShellInternal" GUID="{5af241b7-5627-4d12-bfb1-2b67d11127d7}">
      <Color Name="EnvironmentHeader">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="EnvironmentHeaderInactive">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="EnvironmentTab">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="EnvironmentTabInactive">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="EnvironmentBody">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
      </Color>
      <Color Name="EnvironmentBodyText">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="EnvironmentBackground">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="StatusBarBackgroundFillRest">
        <Background Type="CT_RAW" Source="FF%(chrome)s"/>
      </Color>
      <Color Name="StatusBarTextFillRest">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="StatusBarTextFillDisabled">
        <Background Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="StatusBarControlFillSecondary">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
      </Color>
      <Color Name="EnvironmentBorder">
        <Background Type="CT_RAW" Source="FF%(border)s"/>
      </Color>
      <Color Name="EnvironmentIndicator">
        <Background Type="CT_RAW" Source="FF%(accent)s"/>
      </Color>
      <Color Name="EnvironmentLogo">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="EnvironmentLayeredBackground">
        <Background Type="CT_RAW" Source="61000000"/>
      </Color>
    </Category>

    <Category Name="Environment" GUID="{624ed9c3-bdfd-41fa-96c3-7c824ea32e3d}">
      <Color Name="Window">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
      </Color>
      <Color Name="ToolWindowBackground">
        <Background Type="CT_RAW" Source="FF%(panel)s"/>
      </Color>
      <Color Name="BrandedUIBackground">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
      </Color>
      <Color Name="ScrollBarBackground">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
      </Color>
      <!-- Text in this category lives in the Background slot. Background and
           Foreground are the two slots of a colour entry, not "fill" and "text":
           a colour named ...Text or ...Glyph is single-slot, and Visual Studio
           has nowhere to put a Foreground stated on one. It drops it silently -
           no error, no log - so the theme installs and simply does not paint.
           These three are what the Test Explorer and every other tool window
           bind to; without them the whole text layer falls back to Dark. -->
      <Color Name="ToolWindowText">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="WindowText">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="GridHeadingText">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="CommandBarTextActive">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="CommandBarTextHover">
        <Background Type="CT_RAW" Source="FFFFFFFF"/>
      </Color>
      <Color Name="CommandBarTextInactive">
        <Background Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="CommandBarMenuGlyph">
        <Background Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <!-- Empty Solution Explorer background -->
    <Category Name="TreeView" GUID="{92ecf08e-8b13-4cf4-99e9-ae2692382185}">
      <Color Name="Background">
        <Background Type="CT_RAW" Source="FF%(panel)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <!-- Error List column headers -->
    <Category Name="Header" GUID="{4997f547-1379-456e-b985-2f413cdfa536}">
      <Color Name="Default">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <Category Name="Output Window" GUID="{9973efdf-317d-431c-8bc1-5e88cbfd4f7f}">
      <Color Name="Plain Text">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <Category Name="Find Results" GUID="{5c48b2cb-0366-4fbf-9786-0bb37e945687}">
      <Color Name="Plain Text">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <Category Name="Immediate Window" GUID="{6bb65c5a-2f31-4bde-9f48-8a38dc0c63e7}">
      <Color Name="Plain Text">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <Category Name="Command Window" GUID="{ee1be240-4e81-4beb-8eea-54322b6b1bf5}">
      <Color Name="Plain Text">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
    </Category>

    <!-- ============================= -->
    <!-- Editor surface                -->
    <!-- ============================= -->
    <Category Name="Text Editor Text Manager Items" GUID="{58e96763-1d3b-4e05-b6ba-ff7115fd0b7b}">
      <Color Name="Plain Text">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="Selected Text">
        <Background Type="CT_RAW" Source="FF%(sel)s"/>
        <Foreground Type="CT_AUTOMATIC" Source="00000000"/>
      </Color>
      <Color Name="Inactive Selected Text">
        <Background Type="CT_RAW" Source="FF%(isel)s"/>
        <Foreground Type="CT_AUTOMATIC" Source="00000000"/>
      </Color>
      <Color Name="Visible Whitespace">
        <Foreground Type="CT_RAW" Source="FF%(border)s"/>
      </Color>
      <!-- Indicator Margin is background-only; a Foreground here has no slot. -->
      <Color Name="Indicator Margin">
        <Background Type="CT_RAW" Source="FF%(bg)s"/>
      </Color>
    </Category>

    <Category Name="Text Editor Language Service Items" GUID="{e0187991-b458-4f7e-8ca9-42c9a573b56c}">
      <!-- Fallback for languages without Roslyn. Kept in step with the MEF block below. -->
      <Color Name="Text">
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <!-- Coloured, not plain. This is the fallback used when Roslyn has no
           semantics (unsaved file, file outside a project, workspace still loading,
           non-C# language). Leaving it plain marks such names as "unresolved", but
           it also means a whole file silently loses its name colouring with no
           explanation on screen. These themes exist to make code easier to scan, so
           they favour a name always reading as a name over encoding compiler state
           the reader never asked about. -->
      <Color Name="Identifier">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="Comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="Keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="Preprocessor Keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="Operator">
        <Foreground Type="CT_RAW" Source="FF%(operator)s"/>
      </Color>
      <Color Name="String">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="String(C# @ Verbatim)">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="Number">
        <Foreground Type="CT_RAW" Source="FF%(number)s"/>
      </Color>
      <Color Name="Literal">
        <Foreground Type="CT_RAW" Source="FF%(number)s"/>
      </Color>
      <Color Name="User Types">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="User Types(Value types)">
        <Foreground Type="CT_RAW" Source="FF%(struct)s"/>
      </Color>
      <Color Name="User Types(Interfaces)">
        <Foreground Type="CT_RAW" Source="FF%(interface)s"/>
      </Color>
      <Color Name="User Types(Delegates)">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="User Types(Enums)">
        <Foreground Type="CT_RAW" Source="FF%(enum)s"/>
      </Color>
      <Color Name="User Types(Type parameters)">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <!-- XML -->
      <Color Name="XML Text">
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="XML Keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="XML Delimiter">
        <Foreground Type="CT_RAW" Source="FF%(punct)s"/>
      </Color>
      <Color Name="XML Name">
        <Foreground Type="CT_RAW" Source="FF%(tag)s"/>
      </Color>
      <Color Name="XML Attribute">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="XML Attribute Value">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="XML Comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="XML CData Section">
        <Foreground Type="CT_RAW" Source="FF%(constant)s"/>
      </Color>
      <!-- XAML -->
      <Color Name="XAML Text">
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="XAML Keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="XAML Name">
        <Foreground Type="CT_RAW" Source="FF%(tag)s"/>
      </Color>
      <Color Name="XAML Attribute">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="XAML Attribute Value">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="XAML Comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <!-- HTML / CSS -->
      <Color Name="HTML Element Name">
        <Foreground Type="CT_RAW" Source="FF%(tag)s"/>
      </Color>
      <Color Name="HTML Attribute Name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="HTML Attribute Value">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="HTML Comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="HTML Tag Delimiter">
        <Foreground Type="CT_RAW" Source="FF%(punct)s"/>
      </Color>
      <Color Name="HTML Operator">
        <Foreground Type="CT_RAW" Source="FF%(operator)s"/>
      </Color>
      <Color Name="HTML Entity">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="CSS Keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="CSS Comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="CSS Selector">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="CSS Property Name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="CSS Property Value">
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <Color Name="CSS String Value">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
    </Category>

    <!-- Roslyn classifications -->
    <Category Name="Text Editor MEF Items" GUID="{75a05685-00a8-4ded-bae5-e7a50bfa929a}">
      <!-- Statements and declarations share the keyword hue; control flow is bold
           (FocusEmphasis.cs) -->
      <Color Name="keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="keyword - control">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="preprocessor keyword">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="preprocessor text">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <!-- Types -->
      <Color Name="class name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="struct name">
        <Foreground Type="CT_RAW" Source="FF%(struct)s"/>
      </Color>
      <Color Name="record class name">
        <Foreground Type="CT_RAW" Source="FF%(record)s"/>
      </Color>
      <Color Name="record struct name">
        <Foreground Type="CT_RAW" Source="FF%(record)s"/>
      </Color>
      <Color Name="enum name">
        <Foreground Type="CT_RAW" Source="FF%(enum)s"/>
      </Color>
      <Color Name="module name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="interface name">
        <Foreground Type="CT_RAW" Source="FF%(interface)s"/>
      </Color>
      <Color Name="type parameter name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="delegate name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="array name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="pointer name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="function pointer name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <!-- Methods -->
      <Color Name="method name">
        <Foreground Type="CT_RAW" Source="FF%(method)s"/>
      </Color>
      <Color Name="extension method name">
        <Foreground Type="CT_RAW" Source="FF%(method)s"/>
      </Color>
      <!-- Variables: their own hue. The design mockups leave identifiers at
           plain text, but that collapses locals, fields and
           properties into the same read as punctuation and operators; giving
           them a hue is what makes "what is this name" answerable at a glance. -->
      <Color Name="local name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="field name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="property name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="event name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="parameter name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <Color Name="enum member name">
        <Foreground Type="CT_RAW" Source="FF%(variable)s"/>
      </Color>
      <!-- Literals -->
      <Color Name="string">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="string - verbatim">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="string - escape character">
        <Foreground Type="CT_RAW" Source="FF%(constant)s"/>
      </Color>
      <Color Name="number">
        <Foreground Type="CT_RAW" Source="FF%(number)s"/>
      </Color>
      <Color Name="constant name">
        <Foreground Type="CT_RAW" Source="FF%(constant)s"/>
      </Color>
      <Color Name="label name">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <!-- Structure recedes -->
      <Color Name="operator">
        <Foreground Type="CT_RAW" Source="FF%(operator)s"/>
      </Color>
      <Color Name="operator - overloaded">
        <Foreground Type="CT_RAW" Source="FF%(operator)s"/>
      </Color>
      <Color Name="punctuation">
        <Foreground Type="CT_RAW" Source="FF%(punct)s"/>
      </Color>
      <Color Name="namespace name">
        <Foreground Type="CT_RAW" Source="FF%(punct)s"/>
      </Color>
      <!-- Comments, italic via the MEF component -->
      <Color Name="comment">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="xml doc comment - text">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="xml doc comment - name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="xml doc comment - delimiter">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="xml doc comment - comment">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="xml doc comment - cdata section">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <!-- An attribute inside a doc tag - <typeparam name="T"> - is three more
           classifications, not part of "name". Left out, they render in Dark's
           colours in the middle of an otherwise themed comment. -->
      <Color Name="xml doc comment - attribute name">
        <Foreground Type="CT_RAW" Source="FF%(class)s"/>
      </Color>
      <Color Name="xml doc comment - attribute value">
        <Foreground Type="CT_RAW" Source="FF%(string)s"/>
      </Color>
      <Color Name="xml doc comment - attribute quotes">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="xml doc comment - entity reference">
        <Foreground Type="CT_RAW" Source="FF%(constant)s"/>
      </Color>
      <Color Name="xml doc comment - processing instruction">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <!-- The gutter. Visual Studio registers both of these under MEF Items, not
           under Text Manager Items where a line number intuitively belongs. -->
      <Color Name="Line Number">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <Color Name="Selected Line Number">
        <Foreground Type="CT_RAW" Source="FF%(text)s"/>
      </Color>
      <!-- The inactive side of an #if. Recessive on purpose: it is the one thing
           on screen that is not compiled. -->
      <Color Name="Excluded Code">
        <Foreground Type="CT_RAW" Source="FF%(muted)s"/>
      </Color>
      <!-- Hints are the editor talking, not the code. They sit on the raised
           surface so they read as an overlay rather than as text. -->
      <Color Name="inlay hints">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="inline parameter name hints">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <Color Name="inline hints">
        <Background Type="CT_RAW" Source="FF%(raised)s"/>
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <!-- Inline diagnostics are the compiler answering back at the end of the
           line. Errors take the keyword hue, which is each palette's loudest and
           is otherwise reserved for a mismatched brace; warnings take the enum
           hue, which is warm in every direction without being the alarm colour;
           Edit and Continue is informational and recedes to comment. -->
      <Color Name="inline diagnostics - syntax error">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
      <Color Name="inline diagnostics - compiler warning">
        <Foreground Type="CT_RAW" Source="FF%(enum)s"/>
      </Color>
      <Color Name="inline diagnostics - Edit and Continue">
        <Foreground Type="CT_RAW" Source="FF%(comment)s"/>
      </Color>
      <!-- Roslyn ships `record name` alongside the two specific record kinds. -->
      <Color Name="record name">
        <Foreground Type="CT_RAW" Source="FF%(record)s"/>
      </Color>
      <!-- Brace pairs -->
      <Color Name="brace pair level one">
        <Foreground Type="CT_RAW" Source="FF%(brace1)s"/>
      </Color>
      <Color Name="brace pair level two">
        <Foreground Type="CT_RAW" Source="FF%(brace2)s"/>
      </Color>
      <Color Name="brace pair level three">
        <Foreground Type="CT_RAW" Source="FF%(brace3)s"/>
      </Color>
      <Color Name="mismatched brace">
        <Foreground Type="CT_RAW" Source="FF%(keyword)s"/>
      </Color>
%(regex)s    </Category>

  </Theme>
</Themes>
"""


def main():
    low = 0
    for palette in PALETTES:
        d = derive(palette)
        path = os.path.join(OUTDIR, d["file"])
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(TEMPLATE % d)
        print("wrote %s" % path)

        print("  contrast on #%s:" % d["bg"])
        for key, label, floor in REPORTED:
            ratio = contrast(d[key], d["bg"])
            ok = ratio >= floor
            low += 0 if ok else 1
            note = "" if floor == AA else "   (recessive by design, AA would need %.1f)" % AA
            print("    %s %-11s #%s  %5.2f:1  floor %.1f%s"
                  % ("ok " if ok else "LOW", label, d[key], ratio, floor, note))

        # Closest pairs among the syntax hues. Reported, never repainted: each
        # one is the direction's own trade-off, and two of them are tight by
        # construction -- operator tints keyword, variable tints plain text.
        # Hue is one of three channels here, so read these next to the contrast
        # figures above rather than on their own.
        pairs = []
        for i, a in enumerate(SEPARATED):
            for b in SEPARATED[i + 1:]:
                pairs.append((hue_gap(to_hsl(d[a])[0], to_hsl(d[b])[0]), a, b))
        pairs.sort()

        print("    closest hues:")
        for gap, a, b in pairs[:CLOSEST_REPORTED]:
            print("        %-9s %-9s %3.0f deg apart  %5.2f:1 vs %5.2f:1"
                  % (a, b, gap, contrast(d[a], d["bg"]), contrast(d[b], d["bg"])))
        print("")

    print("done: %d theme(s), %d token(s) below floor" % (len(PALETTES), low))
    return 1 if low else 0


if __name__ == "__main__":
    sys.exit(main())
