// Packaging only. Every colour in this plugin is generated by
// jetbrains/gen-jetbrains.py from scripts/focuspalette.py - nothing here decides
// what anything looks like, and there is no source code to compile.
//
// The plugin exists for one reason the .icls files cannot cover on their own:
// an .icls paints the editor, and only a theme plugin can paint the IDE frame
// around it. Each *.theme.json here points its editorScheme back at the matching
// .icls, so the two halves cannot drift.

import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType

plugins {
    id("org.jetbrains.intellij.platform") version "2.2.1"
}

group = "com.vpcmps"
version = providers.gradleProperty("pluginVersion").get()

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        // Built against the community IDE. A theme plugin has no API surface, so
        // it installs into Rider, PyCharm and every other IntelliJ-based IDE.
        intellijIdeaCommunity(providers.gradleProperty("platformVersion").get())
    }
}

intellijPlatform {
    pluginConfiguration {
        version = providers.gradleProperty("pluginVersion")
        ideaVersion {
            sinceBuild = providers.gradleProperty("pluginSinceBuild")
            // Left open on purpose: a theme cannot break against a newer IDE.
            untilBuild = provider { null }
        }
    }

    publishing {
        // Read from the environment rather than a Gradle property so the token
        // never lands in gradle.properties, a command line, or the build scan.
        // Absent locally, which is what should happen: publishing is a CI job
        // behind a protected environment, not something a checkout can do.
        token = providers.environmentVariable("JETBRAINS_PUBLISH_TOKEN")
    }

    pluginVerification {
        ides {
            // Pinned rather than recommended(). That helper resolves the newest
            // release of every supported major, so the set it asks for changes
            // on JetBrains' release schedule rather than on anything in this
            // repository - and a build started failing on ideaIC:2025.3, a
            // coordinate none of the configured repositories serve.
            //
            // The same platform the plugin is built against is the one worth
            // verifying against, and it comes from the same property so the two
            // cannot drift.
            ide(
                IntelliJPlatformType.IntellijIdeaCommunity,
                providers.gradleProperty("platformVersion").get(),
            )
        }
    }
}

// The resources are generated, so a build that runs before the generator would
// silently package whatever was there last time. Fail loudly instead.
val checkGeneratedThemes by tasks.registering {
    val themes = layout.projectDirectory.dir("src/main/resources/themes")
    doFirst {
        val files = themes.asFile.listFiles().orEmpty()
        val schemes = files.count { it.name.endsWith(".icls") }
        val descriptors = files.count { it.name.endsWith(".theme.json") }
        require(schemes > 0 && schemes == descriptors) {
            "src/main/resources/themes holds $schemes .icls and $descriptors " +
                ".theme.json files. Run: python jetbrains/gen-jetbrains.py"
        }
    }
}

tasks.named("processResources") {
    dependsOn(checkGeneratedThemes)
}
